# Default values for streamingapp
image:
  registry: 975050024946.dkr.ecr.eu-west-2.amazonaws.com
  prefix: jatin-streamingapp
  tag: "latest"
  pullPolicy: Always

# GLOBAL Environment Variables (Shared by all services)
env:
  NODE_ENV: production
  # Use the internal DNS name of the mongo pod we just installed
  MONGO_URI: "mongodb://mongodb.production.svc.cluster.local:27017/streamingapp"
  JWT_SECRET: "changeme"

# Auth Service Configuration
authService:
  name: auth-service
  replicaCount: 1
  port: 3001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256"
      cpu: "300"

# Streaming Service Configuration
streamingService:
  name: streaming-service
  replicaCount: 1
  port: 3002
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

# Admin Service Configuration
adminService:
  name: admin-service
  replicaCount: 1
  port: 3003
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

# Chat Service Configuration
chatService:
  name: chat-service
  replicaCount: 1
  port: 3004
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

# Frontend Configuration
frontend:
  name: frontend
  replicaCount: 1
  port: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

# Ingress Configuration
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: api.streamingapp.com

# Environment variables
env:
  NODE_ENV: production
