apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adminService.name }}
  labels:
    app: {{ .Values.adminService.name }}
spec:
  replicas: {{ .Values.adminService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.adminService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminService.name }}
    spec:
      containers:
      - name: {{ .Values.adminService.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.prefix }}/admin:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.adminService.port }}
        env:
        - name: NODE_ENV
          value: {{ .Values.env.NODE_ENV }}
        - name: PORT
          value: "{{ .Values.adminService.port }}"
        resources:
          {{- toYaml .Values.adminService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminService.name }}
spec:
  selector:
    app: {{ .Values.adminService.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.adminService.port }}
    targetPort: {{ .Values.adminService.port }}
  type: ClusterIP
